version: 1.2
workflows:
- name: HGSVC2Align
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/HGSVC2Align.wdl
  testParameterFiles:
- name: HGSVC2DownloadAssemblies
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/HGSVC2DownloadAssemblies.wdl
  testParameterFiles:
- name: HGSVC2Download
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/HGSVC2Download.wdl
  testParameterFiles:
