version: 1.2
workflows:
- name: HGSVC2Align
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/HGSVC2Align.wdl
  testParameterFiles:
- name: HGSVC2DownloadAssemblies
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/HGSVC2DownloadAssemblies.wdl
  testParameterFiles:
- name: HGSVC2Download
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/HGSVC2Download.wdl
  testParameterFiles:
- name: SVMerger
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/SVMerger.wdl
  testParameterFiles:
- name: Svimmer
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Svimmer.wdl
  testParameterFiles:
- name: SVMergerIntersample
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/SVMergerIntersample.wdl
  testParameterFiles:
- name: SvimmerIntersample
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/SvimmerIntersample.wdl
  testParameterFiles:
- name: BcftoolsMerge
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/BcftoolsMerge.wdl
  testParameterFiles:
- name: BcftoolsMergeDipcall
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/BcftoolsMergeDipcall.wdl
  testParameterFiles: