version: 1.2
workflows:
- name: HGSVC2Align
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/HGSVC2Align.wdl
  testParameterFiles:
- name: HGSVC2DownloadAssemblies
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/HGSVC2DownloadAssemblies.wdl
  testParameterFiles:
- name: HGSVC2Download
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/HGSVC2Download.wdl
  testParameterFiles:
- name: SVMerger
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/SVMerger.wdl
  testParameterFiles:
- name: Svimmer
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Svimmer.wdl
  testParameterFiles:
- name: SVMergerIntersample
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/SVMergerIntersample.wdl
  testParameterFiles:
- name: SvimmerIntersample
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/SvimmerIntersample.wdl
  testParameterFiles:
- name: BcftoolsMerge
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/BcftoolsMerge.wdl
  testParameterFiles:
- name: BcftoolsMergeDipcall
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/BcftoolsMergeDipcall.wdl
  testParameterFiles:
- name: Jasmine
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Jasmine.wdl
  testParameterFiles:
- name: JasmineIntersample
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/JasmineIntersample.wdl
  testParameterFiles:
- name: SnifflesIntersample
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/SnifflesIntersample.wdl
  testParameterFiles:
- name: HPRCDownloadClones
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/HPRCDownloadClones.wdl
  testParameterFiles:
- name: SvpopIntra
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/SvpopIntra.wdl
  testParameterFiles:
- name: PbsvIntersample
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/PbsvIntersample.wdl
  testParameterFiles:
- name: TruvariIntersample
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/TruvariIntersample.wdl
  testParameterFiles:
- name: ROC
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/ROC.wdl
  testParameterFiles:
- name: PAV2SVs
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/PAV2SVs.wdl
  testParameterFiles:
- name: GetRegenotypedTruePositives
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/GetRegenotypedTruePositives.wdl
  testParameterFiles:
- name: GetRegenotypedVcf
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/GetRegenotypedVcf.wdl
  testParameterFiles:
- name: GetRegenotypedVcfSniffles
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/GetRegenotypedVcfSniffles.wdl
  testParameterFiles:
- name: GetRegenotypedVcfKanpig
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/GetRegenotypedVcfKanpig.wdl
  testParameterFiles:
- name: TruvariIntrasampleFabio
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/TruvariIntrasampleFabio.wdl
  testParameterFiles:
- name: FilterAndSplit
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/FilterAndSplit.wdl
  testParameterFiles:
- name: ConcatenateChromosomes
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/ConcatenateChromosomes.wdl
  testParameterFiles:
- name: ToBed
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/ToBed.wdl
  testParameterFiles:
- name: GetRegenotypedVcfKanpigMerged
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/GetRegenotypedVcfKanpigMerged.wdl
  testParameterFiles:
- name: MergeRegenotypedIntersampleVcf
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/MergeRegenotypedIntersampleVcf.wdl
  testParameterFiles:
- name: AddTruvariAnnotations
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/AddTruvariAnnotations.wdl
  testParameterFiles:
- name: AnnotateJointVcf
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/AnnotateJointVcf.wdl
  testParameterFiles:    
- name: Hapdiff
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Hapdiff.wdl
  testParameterFiles:      
- name: Dipcall2SVs
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Dipcall2SVs.wdl
  testParameterFiles:      
