ROOT_DIR='/Users/fcunial/Downloads/sniffles-gt';
QUANTITY_NAME='AD';  % 'AD'  'DV'  'GQ'
FONT_SIZE=14;

figure(1);



% ----------------------------- ROC CURVES -------------------------------------

ALL=load(sprintf('%s/roc_calls_%s_geq.txt',ROOT_DIR,QUANTITY_NAME));
DEL=load(sprintf('%s/roc_del_%s_geq.txt',ROOT_DIR,QUANTITY_NAME));
INS=load(sprintf('%s/roc_ins_%s_geq.txt',ROOT_DIR,QUANTITY_NAME));

subplot(2,3,1); hold on; 
plot(ALL(:,2),ALL(:,3),'.-');
plot(DEL(:,2),DEL(:,3),'.-');
plot(INS(:,2),INS(:,3),'.-');
line([0,1],[0,1],'color','black');
axis square; grid on; xlabel('False positive rate','fontsize',FONT_SIZE); 
ylabel('True positive rate','fontsize',FONT_SIZE);
title(sprintf('ROC - Large %s',QUANTITY_NAME),'fontsize',FONT_SIZE);

subplot(2,3,2); hold on;
plot(ALL(:,1),ALL(:,2),'.-');
plot(DEL(:,1),DEL(:,2),'.-');
plot(INS(:,1),INS(:,2),'.-');
axis square; grid on; xlabel(QUANTITY_NAME,'fontsize',FONT_SIZE); 
ylabel('False positive rate','fontsize',FONT_SIZE);
legend('all','DEL','INS','location','northeast','fontsize',FONT_SIZE); title(sprintf('False positive rate - Large %s',QUANTITY_NAME),'fontsize',FONT_SIZE);

ALL=load(sprintf('%s/histogram_calls_%s.txt',ROOT_DIR,QUANTITY_NAME));
DEL=load(sprintf('%s/histogram_del_%s.txt',ROOT_DIR,QUANTITY_NAME));
INS=load(sprintf('%s/histogram_ins_%s.txt',ROOT_DIR,QUANTITY_NAME));

subplot(2,3,3); hold on;
plot(ALL(:,1),flip(cumsum(flip(ALL(:,2)./sum(ALL(:,2))))),'.-');
plot(DEL(:,1),flip(cumsum(flip(DEL(:,2)./sum(DEL(:,2))))),'.-');
plot(INS(:,1),flip(cumsum(flip(INS(:,2)./sum(INS(:,2))))),'.-');
axis square; grid on; xlabel(QUANTITY_NAME,'fontsize',FONT_SIZE); 
ylabel('Fraction of calls','fontsize',FONT_SIZE);
legend('all','DEL','INS','location','northeast','fontsize',FONT_SIZE); title(sprintf('Fraction of calls with large %s',QUANTITY_NAME),'fontsize',FONT_SIZE);

subplot(2,3,6); hold on;
plot(ALL(:,1),cumsum(ALL(:,2)./sum(ALL(:,2))),'.-');
plot(DEL(:,1),cumsum(DEL(:,2)./sum(DEL(:,2))),'.-');
plot(INS(:,1),cumsum(INS(:,2)./sum(INS(:,2))),'.-');
axis square; grid on; xlabel(QUANTITY_NAME,'fontsize',FONT_SIZE); 
ylabel('Fraction of calls','fontsize',FONT_SIZE);
legend('all','DEL','INS','location','southeast','fontsize',FONT_SIZE); title(sprintf('Fraction of calls with small %s',QUANTITY_NAME),'fontsize',FONT_SIZE);

ALL=load(sprintf('%s/roc_calls_%s_leq.txt',ROOT_DIR,QUANTITY_NAME));
DEL=load(sprintf('%s/roc_del_%s_leq.txt',ROOT_DIR,QUANTITY_NAME));
INS=load(sprintf('%s/roc_ins_%s_leq.txt',ROOT_DIR,QUANTITY_NAME));

subplot(2,3,4); hold on; 
plot(ALL(:,2),ALL(:,3),'.-');
plot(DEL(:,2),DEL(:,3),'.-');
plot(INS(:,2),INS(:,3),'.-');
line([0,1],[0,1],'color','black');
axis square; grid on; xlabel('False positive rate','fontsize',FONT_SIZE); 
ylabel('True positive rate','fontsize',FONT_SIZE);
legend('all','DEL','INS','location','northwest','fontsize',FONT_SIZE); title(sprintf('ROC - Small %s',QUANTITY_NAME),'fontsize',FONT_SIZE);

subplot(2,3,5); hold on;
plot(ALL(:,1),ALL(:,2),'.-');
plot(DEL(:,1),DEL(:,2),'.-');
plot(INS(:,1),INS(:,2),'.-');
axis square; grid on; xlabel(QUANTITY_NAME,'fontsize',FONT_SIZE); 
ylabel('False positive rate','fontsize',FONT_SIZE); title(sprintf('False positive rate - Small %s',QUANTITY_NAME),'fontsize',FONT_SIZE);




% --------------------------- SUPPORTING CALLERS -------------------------------

A=load(sprintf('%s/2callers_merged.txt',ROOT_DIR));
N_CALLS_ALL=A(1); N_DEL_ALL=A(2); N_INS_ALL=A(3); 
N_CALLS_2=A(4); N_DEL_2=A(5); N_INS_2=A(6);
N_CALLS_3=A(7); N_DEL_3=A(8); N_INS_3=A(9);
N_CALLS_PBSV_SNIFFLES=A(10); N_DEL_PBSV_SNIFFLES=A(11); N_INS_PBSV_SNIFFLES=A(12);
N_CALLS_PBSV_PAV=A(13); N_DEL_PBSV_PAV=A(14); N_INS_PBSV_PAV=A(15);
N_CALLS_SNIFFLES_PAV=A(16); N_DEL_SNIFFLES_PAV=A(17); N_INS_SNIFFLES_PAV=A(18);
N_CALLS_PBSV=A(19); N_DEL_PBSV=A(20); N_INS_PBSV=A(21); 
N_CALLS_SNIFFLES=A(22); N_DEL_SNIFFLES=A(23); N_INS_SNIFFLES=A(24); 
N_CALLS_PAV=A(25); N_DEL_PAV=A(26); N_INS_PAV=A(27); 

A=load(sprintf('%s/2callers_tp.txt',ROOT_DIR));
N_TP=A(1); N_DEL_TP=A(2); N_INS_TP=A(3);
N_TP_2=A(4); N_DEL_TP_2=A(5); N_INS_TP_2=A(6);
N_TP_3=A(7); N_DEL_TP_3=A(8); N_INS_TP_3=A(9);
N_TP_PBSV_SNIFFLES=A(10); N_DEL_TP_PBSV_SNIFFLES=A(11); N_INS_TP_PBSV_SNIFFLES=A(12);
N_TP_PBSV_PAV=A(13); N_DEL_TP_PBSV_PAV=A(14); N_INS_TP_PBSV_PAV=A(15);
N_TP_SNIFFLES_PAV=A(16); N_DEL_TP_SNIFFLES_PAV=A(17); N_INS_TP_SNIFFLES_PAV=A(18);
N_TP_PBSV=A(19); N_DEL_TP_PBSV=A(20); N_INS_TP_PBSV=A(21); 
N_TP_SNIFFLES=A(22); N_DEL_TP_SNIFFLES=A(23); N_INS_TP_SNIFFLES=A(24); 
N_TP_PAV=A(25); N_DEL_TP_PAV=A(26); N_INS_TP_PAV=A(27); 

# >=2 CALLERS
# All calls
TRUE_POSITIVES=N_TP_2;
FALSE_POSITIVES=N_CALLS_2-TRUE_POSITIVES;
TRUE_NEGATIVES=N_CALLS_ALL-N_TP-FALSE_POSITIVES;
FALSE_NEGATIVES=N_TP-TRUE_POSITIVES;
subplot(2,3,1); plot(FALSE_POSITIVES/(FALSE_POSITIVES+TRUE_NEGATIVES),TRUE_POSITIVES/(TRUE_POSITIVES+FALSE_NEGATIVES),'o');
# DEL
TRUE_POSITIVES=N_DEL_TP_2;
FALSE_POSITIVES=N_DEL_2-TRUE_POSITIVES;
TRUE_NEGATIVES=N_DEL_ALL-N_DEL_TP-FALSE_POSITIVES;
FALSE_NEGATIVES=N_DEL_TP-TRUE_POSITIVES;
subplot(2,3,1); plot(FALSE_POSITIVES/(FALSE_POSITIVES+TRUE_NEGATIVES),TRUE_POSITIVES/(TRUE_POSITIVES+FALSE_NEGATIVES),'o');
# INS
TRUE_POSITIVES=N_INS_TP_2;
FALSE_POSITIVES=N_INS_2-TRUE_POSITIVES;
TRUE_NEGATIVES=N_INS_ALL-N_INS_TP-FALSE_POSITIVES;
FALSE_NEGATIVES=N_INS_TP-TRUE_POSITIVES;
subplot(2,3,1); plot(FALSE_POSITIVES/(FALSE_POSITIVES+TRUE_NEGATIVES),TRUE_POSITIVES/(TRUE_POSITIVES+FALSE_NEGATIVES),'o');

# =3 CALLERS
# All calls
TRUE_POSITIVES=N_TP_3;
FALSE_POSITIVES=N_CALLS_3-TRUE_POSITIVES;
TRUE_NEGATIVES=N_CALLS_ALL-N_TP-FALSE_POSITIVES;
FALSE_NEGATIVES=N_TP-TRUE_POSITIVES;
subplot(2,3,1); plot(FALSE_POSITIVES/(FALSE_POSITIVES+TRUE_NEGATIVES),TRUE_POSITIVES/(TRUE_POSITIVES+FALSE_NEGATIVES),'+');
% # DEL
% TRUE_POSITIVES=N_DEL_TP_3;
% FALSE_POSITIVES=N_DEL_3-TRUE_POSITIVES;
% TRUE_NEGATIVES=N_DEL_ALL-N_DEL_TP-FALSE_POSITIVES;
% FALSE_NEGATIVES=N_DEL_TP-TRUE_POSITIVES;
% subplot(2,3,1); plot(FALSE_POSITIVES/(FALSE_POSITIVES+TRUE_NEGATIVES),TRUE_POSITIVES/(TRUE_POSITIVES+FALSE_NEGATIVES),'+');
% # INS
% TRUE_POSITIVES=N_INS_TP_3;
% FALSE_POSITIVES=N_INS_3-TRUE_POSITIVES;
% TRUE_NEGATIVES=N_INS_ALL-N_INS_TP-FALSE_POSITIVES;
% FALSE_NEGATIVES=N_INS_TP-TRUE_POSITIVES;
% subplot(2,3,1); plot(FALSE_POSITIVES/(FALSE_POSITIVES+TRUE_NEGATIVES),TRUE_POSITIVES/(TRUE_POSITIVES+FALSE_NEGATIVES),'+');

# PBSV+SNIFFLES
# All calls
TRUE_POSITIVES=N_TP_PBSV_SNIFFLES
FALSE_POSITIVES=N_CALLS_PBSV_SNIFFLES-TRUE_POSITIVES
TRUE_NEGATIVES=N_CALLS_ALL-N_TP-FALSE_POSITIVES
FALSE_NEGATIVES=N_TP-TRUE_POSITIVES
subplot(2,3,1); plot(FALSE_POSITIVES/(FALSE_POSITIVES+TRUE_NEGATIVES),TRUE_POSITIVES/(TRUE_POSITIVES+FALSE_NEGATIVES),'*');
% # DEL
% TRUE_POSITIVES=N_DEL_TP_PBSV_SNIFFLES;
% FALSE_POSITIVES=N_DEL_PBSV_SNIFFLES-TRUE_POSITIVES;
% TRUE_NEGATIVES=N_DEL_ALL-N_DEL_TP-FALSE_POSITIVES;
% FALSE_NEGATIVES=N_DEL_TP-TRUE_POSITIVES;
% subplot(2,3,1); plot(FALSE_POSITIVES/(FALSE_POSITIVES+TRUE_NEGATIVES),TRUE_POSITIVES/(TRUE_POSITIVES+FALSE_NEGATIVES),'*');
% # INS
% TRUE_POSITIVES=N_INS_TP_PBSV_SNIFFLES;
% FALSE_POSITIVES=N_INS_PBSV_SNIFFLES-TRUE_POSITIVES;
% TRUE_NEGATIVES=N_INS_ALL-N_INS_TP-FALSE_POSITIVES;
% FALSE_NEGATIVES=N_INS_TP-TRUE_POSITIVES;
% subplot(2,3,1); plot(FALSE_POSITIVES/(FALSE_POSITIVES+TRUE_NEGATIVES),TRUE_POSITIVES/(TRUE_POSITIVES+FALSE_NEGATIVES),'*');

# PBSV+PAV
# All calls
TRUE_POSITIVES=N_TP_PBSV_PAV;
FALSE_POSITIVES=N_CALLS_PBSV_PAV-TRUE_POSITIVES;
TRUE_NEGATIVES=N_CALLS_ALL-N_TP-FALSE_POSITIVES;
FALSE_NEGATIVES=N_TP-TRUE_POSITIVES;
subplot(2,3,1); plot(FALSE_POSITIVES/(FALSE_POSITIVES+TRUE_NEGATIVES),TRUE_POSITIVES/(TRUE_POSITIVES+FALSE_NEGATIVES),'x');
% # DEL
% TRUE_POSITIVES=N_DEL_TP_PBSV_PAV;
% FALSE_POSITIVES=N_DEL_PBSV_PAV-TRUE_POSITIVES;
% TRUE_NEGATIVES=N_DEL_ALL-N_DEL_TP-FALSE_POSITIVES;
% FALSE_NEGATIVES=N_DEL_TP-TRUE_POSITIVES;
% subplot(2,3,1); plot(FALSE_POSITIVES/(FALSE_POSITIVES+TRUE_NEGATIVES),TRUE_POSITIVES/(TRUE_POSITIVES+FALSE_NEGATIVES),'x');
% # INS
% TRUE_POSITIVES=N_INS_TP_PBSV_PAV;
% FALSE_POSITIVES=N_INS_PBSV_PAV-TRUE_POSITIVES;
% TRUE_NEGATIVES=N_INS_ALL-N_INS_TP-FALSE_POSITIVES;
% FALSE_NEGATIVES=N_INS_TP-TRUE_POSITIVES;
% subplot(2,3,1); plot(FALSE_POSITIVES/(FALSE_POSITIVES+TRUE_NEGATIVES),TRUE_POSITIVES/(TRUE_POSITIVES+FALSE_NEGATIVES),'x');

# SNIFFLES+PAV
# All calls
TRUE_POSITIVES=N_TP_SNIFFLES_PAV;
FALSE_POSITIVES=N_CALLS_SNIFFLES_PAV-TRUE_POSITIVES;
TRUE_NEGATIVES=N_CALLS_ALL-N_TP-FALSE_POSITIVES;
FALSE_NEGATIVES=N_TP-TRUE_POSITIVES;
subplot(2,3,1); plot(FALSE_POSITIVES/(FALSE_POSITIVES+TRUE_NEGATIVES),TRUE_POSITIVES/(TRUE_POSITIVES+FALSE_NEGATIVES),'s');
% # DEL
% TRUE_POSITIVES=N_DEL_TP_SNIFFLES_PAV;
% FALSE_POSITIVES=N_DEL_SNIFFLES_PAV-TRUE_POSITIVES;
% TRUE_NEGATIVES=N_DEL_ALL-N_DEL_TP-FALSE_POSITIVES;
% FALSE_NEGATIVES=N_DEL_TP-TRUE_POSITIVES;
% subplot(2,3,1); plot(FALSE_POSITIVES/(FALSE_POSITIVES+TRUE_NEGATIVES),TRUE_POSITIVES/(TRUE_POSITIVES+FALSE_NEGATIVES),'s');
% # INS
% TRUE_POSITIVES=N_INS_TP_SNIFFLES_PAV;
% FALSE_POSITIVES=N_INS_SNIFFLES_PAV-TRUE_POSITIVES;
% TRUE_NEGATIVES=N_INS_ALL-N_INS_TP-FALSE_POSITIVES;
% FALSE_NEGATIVES=N_INS_TP-TRUE_POSITIVES;
% subplot(2,3,1); plot(FALSE_POSITIVES/(FALSE_POSITIVES+TRUE_NEGATIVES),TRUE_POSITIVES/(TRUE_POSITIVES+FALSE_NEGATIVES),'s');

# PBSV
# All calls
TRUE_POSITIVES=N_TP_PBSV;
FALSE_POSITIVES=N_CALLS_PBSV-TRUE_POSITIVES;
TRUE_NEGATIVES=N_CALLS_ALL-N_TP-FALSE_POSITIVES;
FALSE_NEGATIVES=N_TP-TRUE_POSITIVES;
subplot(2,3,1); plot(FALSE_POSITIVES/(FALSE_POSITIVES+TRUE_NEGATIVES),TRUE_POSITIVES/(TRUE_POSITIVES+FALSE_NEGATIVES),'^');

# SNIFFLES
# All calls
TRUE_POSITIVES=N_TP_SNIFFLES;
FALSE_POSITIVES=N_CALLS_SNIFFLES-TRUE_POSITIVES;
TRUE_NEGATIVES=N_CALLS_ALL-N_TP-FALSE_POSITIVES;
FALSE_NEGATIVES=N_TP-TRUE_POSITIVES;
subplot(2,3,1); plot(FALSE_POSITIVES/(FALSE_POSITIVES+TRUE_NEGATIVES),TRUE_POSITIVES/(TRUE_POSITIVES+FALSE_NEGATIVES),'>');

# PAV
# All calls
TRUE_POSITIVES=N_TP_PAV;
FALSE_POSITIVES=N_CALLS_PAV-TRUE_POSITIVES;
TRUE_NEGATIVES=N_CALLS_ALL-N_TP-FALSE_POSITIVES;
FALSE_NEGATIVES=N_TP-TRUE_POSITIVES;
subplot(2,3,1); plot(FALSE_POSITIVES/(FALSE_POSITIVES+TRUE_NEGATIVES),TRUE_POSITIVES/(TRUE_POSITIVES+FALSE_NEGATIVES),'v');

%legend('all','DEL','INS','random','\geq2 all','\geq2 DEL','\geq2 INS','=3 all','=3 DEL','=3 INS','pbsv+snf all','pbsv+snf DEL','pbsv+snf INS','pbsv+pav all','pbsv+pav DEL','pbsv+pav INS','snf+pav all','snf+pav DEL','snf+pav INS','location','northeast','fontsize',FONT_SIZE);
legend('all','DEL','INS','random','\geq2 all','\geq2 DEL','\geq2 INS','=3 all','pbsv+snf all','pbsv+pav all','snf+pav all','pbsv all','sniffles all','pav all','location','northeast','fontsize',FONT_SIZE);



% ---------------------------- ANALYSIS OF DV=0 --------------------------------

figure(2);
A=load(sprintf('%s/dv0.txt',ROOT_DIR));
N_CALLS=A(1);
N_CALLS_PBSV=A(2);
N_CALLS_SNIFFLES=A(3);
N_CALLS_PAV=A(4);

N_DEL=A(5); 
N_DEL_PBSV=A(6);
N_DEL_SNIFFLES=A(7);
N_DEL_PAV=A(8);

N_INS=A(9);
N_INS_PBSV=A(10);
N_INS_SNIFFLES=A(11);
N_INS_PAV=A(12);

N_CALLS_GEQ2=A(13);
N_DEL_GEQ2=A(14);
N_INS_GEQ2=A(15);

N_CALLS_ZERO=A(16);
N_DEL_ZERO=A(17);
N_INS_ZERO=A(18);
A=[ [N_CALLS_PBSV./N_CALLS; N_CALLS_SNIFFLES./N_CALLS; N_CALLS_PAV./N_CALLS; N_CALLS_GEQ2./N_CALLS; N_CALLS_ZERO./N_CALLS],   ...
    [N_DEL_PBSV./N_DEL; N_DEL_SNIFFLES./N_DEL; N_DEL_PAV./N_DEL; N_DEL_GEQ2./N_DEL; N_DEL_ZERO./N_DEL],   ...
    [N_INS_PBSV./N_INS; N_INS_SNIFFLES./N_INS; N_INS_PAV./N_INS; N_INS_GEQ2./N_INS; N_INS_ZERO./N_INS] ]
bar(A.','stacked'); title('DV=0 calls','fontsize',FONT_SIZE); axis square; grid on;
xticks([1,2,3]); xticklabels({'all','DEL','INS'}); axis([0,4,0,1]);
legend('pbsv only','sniffles only','pav only','\geq 2 callers','0 callers','fontsize',FONT_SIZE);
